# 基础镜像
FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# 安装 Corepack 
RUN corepack enable

# 设置工作目录  
WORKDIR /app

# 复制项目代码
COPY . .

# 安装依赖并构建项目
FROM base AS prod-deps
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

FROM base AS build
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
RUN pnpm run build

# 定义最终的镜像
FROM nginx:alpine
WORKDIR /usr/share/nginx/html

# Remove default nginx static files
RUN rm -rf ./*

COPY --from=build /app/dist .

# ENTRYPOINT关键字的作用：启动容器时,运行除默认行为外添加的命令
# nginx","-g","daemon off 设置nginx以前台运行
# 这样可以保证nginx进程一直处于运行状态，响应请求时也不会受到容器后台运行的影响。此外，在使用"daemon off"参数时，nginx还会输出一些日志信息到标准输出中，这些信息可以很方便地在控制台中查看，帮助我们更好地了解nginx的运行情况。
ENTRYPOINT ["nginx","-g","daemon off;"]


